name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Test 1
      run: dotnet test ./test/azmi-commandline-tests/azmi-commandline-tests.csproj --verbosity normal
    - name: Test 2
      run: dotnet test ./test/azmi-main-tests/azmi-main-tests.csproj --verbosity normal
